### ISSUE TITLE
AttributeError: 'list' object has no attribute 'lower'

### ISSUE THREAD

**Issue by fengyulin001** [Hanscal/DCKS#4]
Hello, I'm running the code with the problem shown in the picture. But can't find a solution. I hope I can get your help. I will be grateful if it is possible.
![2](https://github.com/Hanscal/DCKS/assets/100842329/b45fa397-4da9-4aba-9132-58b9e2ea06f9)
![Uploading 619MSU}4SR~6BV3P`QSNFMO.png…]()

**Comment by juanmaoxiongmaoQAQ** [comment]
I encountered the same problem, did you solve it? How was it solved?

**Comment by RanQChi** [comment]
go to "src/utils/metrics.py" file 
find "dialogue_evaluation function"
change 
"results1 = RougeEvaluator(num_parallel_calls=1, tokenization_fn=normalize_answer).run_evaluation(**cands**, **golds**)"

into

"results1 = RougeEvaluator(num_parallel_calls=1, tokenization_fn=normalize_answer).run_evaluation(**ori_cands**, **ori_golds**)
"

Just because the Input required ["Good morning."] instead of ["Good","morning","."]

**Comment by fengyulin001** [comment]
OSError: [Errno 28] No space left on device
Thanks for your help, the code runs but there is still a problem can you look at it again for me?

**Comment by fengyulin001** [comment]
![_JZZQ1N L@{{}MY7%F_S4`I](https://github.com/Hanscal/DCKS/assets/100842329/9cf27a33-b5d6-4352-bc25-b218e72f8c55)

**Comment by RanQChi** [comment]
> OSError: [Errno 28] No space left on device Thanks for your help, the code runs but there is still a problem can you look at it again for me?

just because your device is full... there is no space to save the data or results....
try to remove some unused  or useless documents or soft...
another solution is to find another device or place to save...

**Comment by fengyulin001** [comment]
Thank you for your help.
